module.exports = {
    "threshold":5,
    "keys":[],
    "accounts":
    [
        {
            "permission":
                {
                    "actor":"blindblocart","permission":"active"
                },
            "weight":1
        },
        {
            "permission":
                {
                    "actor":"caleosblocks","permission":"active"
                },
            "weight":1
        },
        {
            "permission":
                {
                    "actor":"eosbarcelona","permission":"active"
                },
            "weight":1
        },
        {
            "permission":
                {
                    "actor":"eosmetaliobp","permission":"active"
                },
            "weight":1
        },
        {
            "permission":
                {
                    "actor":"kainosblkpro","permission":"active"
                },
            "weight":1
        },
        { "permission":
                {
                    "actor":"tlsvenezuela","permission":"active"
                },
            "weight":1
        }
    ],
        "waits": []
};