module.exports = {
  "threshold":7,
  "keys":[],
  "accounts":
  [
    {
      "permission":
      {
        "actor":"tframownera","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerb","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerc","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerd","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownere","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerf","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerg","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerh","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframowneri","permission":"active"
      },
      "weight":1
    }
  ],
  "waits": []
};
