module.exports = {
  "threshold":7,
  "keys":[],
  "accounts":
  [
    {
      "permission":
      {
        "actor":"tframlownra","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrb","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrc","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrd","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownre","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrf","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrg","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrh","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownri","permission":"active"
      },
      "weight":1
    }
  ],
  "waits": []
};