module.exports = {
  "threshold":7,
  "keys":[],
  "accounts":
  [
    {
      "permission":
      {
        "actor":"tframowneraa","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerbb","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownercc","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerdd","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframowneree","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerff","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownergg","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerhh","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframownerii","permission":"active"
      },
      "weight":1
    }
  ],
  "waits": []
};
