module.exports = {
  "threshold":2,
  "keys":[],
  "accounts":
  [
    {
      "permission":
      {
        "actor":"tframactivea","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframactiveb","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframactivec","permission":"active"
      },
      "weight":1
    },
  ],
  "waits": []
};
