module.exports = {
  "threshold":7,
  "keys":[],
  "accounts":
  [
    {
      "permission":
      {
        "actor":"tframlownraa","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrbb","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrcc","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrdd","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownree","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrff","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrgg","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrhh","permission":"active"
      },
      "weight":1
    },
    {
      "permission":
      {
        "actor":"tframlownrii","permission":"active"
      },
      "weight":1
    }
  ],
  "waits": []
};